/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adventofcode.pkg2016;

import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author QDS
 */
public class Day6 {
    public static void main(String args[])
    {
        String[] list = {"yyzfkpnq",
"jywprukn",
"wsovudpi",
"xrexczjp",
"lxxexnke",
"yzcrsvfl",
"hfmjylbr",
"echansea",
"soqtipnu",
"kcczgkjs",
"tkxqkyvb",
"cphlzynq",
"mlpbiksm",
"zsyekvjv",
"xxzxstxx",
"bvqgygvh",
"dtxnlzib",
"unukvrmw",
"szarrcqn",
"zpovpibu",
"igmwyioj",
"orausztk",
"zguoanfz",
"uwcamvjp",
"ijlzaeyb",
"thwdcryp",
"zcwxmdxc",
"jwrmtdbx",
"zqxyrskh",
"ufoohfap",
"aodyaarr",
"mxcbalhx",
"tzpyurir",
"nxxpdfso",
"ocioakza",
"ymsuqgzy",
"uzsfureu",
"motqekjl",
"cnfrigwc",
"qorjiulb",
"rbsixwqi",
"ptxfbmef",
"jhwopfrl",
"ugcsqhom",
"mkomobos",
"wbcexznu",
"impsluue",
"ebojtrvp",
"mscyhvwe",
"jnnjykgz",
"icobfeeh",
"qscuwdkx",
"ozeilhke",
"btrlvsog",
"sfewiwzr",
"tptfsoru",
"mlpzsmqf",
"errxvttw",
"kqgynlka",
"fujmsmjp",
"cufdkgyi",
"qfqotxvy",
"bhytijml",
"aueqkddy",
"cnbxutls",
"lsmsdgra",
"ndjqohpk",
"txncbjvv",
"drvgidhf",
"hlifeweo",
"znxeddna",
"fdugqlii",
"bcjwnjyl",
"idrjqtmr",
"gechofdk",
"vqriafnm",
"jkaoskuf",
"lqidragl",
"kktqqqcy",
"uqihlagh",
"cslabmoa",
"haztkzfl",
"dtzxfuud",
"yusadhzr",
"lyjwyywa",
"kqkioixv",
"fernopuc",
"cgeswuhf",
"jbikrerm",
"rnvgflse",
"urqvfxqs",
"ogbjxnqh",
"ypfjnogw",
"szeszjfw",
"ddggwcrc",
"iisvlkaz",
"ctnmxreg",
"styixlfp",
"bmtulfok",
"tjatbqpv",
"sbqtefuj",
"bxdqezrg",
"enqwugon",
"palqwsdx",
"htgethby",
"kqzqkhom",
"fxpyogvx",
"pcggwrmq",
"bexolzrd",
"tyhzuxrj",
"rnpxgwtp",
"rjassgcj",
"zaepiryv",
"gueppvdl",
"vrvhxyak",
"zzjfaxiq",
"ofvwgjsb",
"wljxbsww",
"zadwiivt",
"tdjtsqoa",
"phmsorex",
"hjyjitfq",
"mxivbtuo",
"vgwnrdkh",
"uiuxqiar",
"lyfqhikf",
"sldnbsee",
"nakjrqrv",
"yzpptezp",
"dtnlnoii",
"sgcxoemt",
"mxuxcjds",
"fzbawcuk",
"wpslbtdo",
"fvhfvsuy",
"fgjpefjn",
"xnlfkcnv",
"itucclph",
"fuuxuiqh",
"qgtbjfgw",
"zakxlysq",
"srmwofsh",
"dtjvuhtn",
"fmhinrkc",
"eyxffjqy",
"bqjdculb",
"hvfdufhz",
"cwaukzzq",
"pmqtvpfu",
"seuyiwht",
"jcdyawhy",
"aljrcshh",
"gmehbldw",
"jsgzroht",
"vjyysjjy",
"njbmtbna",
"atqmtjcc",
"xlakorgr",
"dsgvcmer",
"gpiisgfj",
"jlycgznr",
"wxhsfonh",
"sgphbiye",
"bhfcrvsd",
"vvyfxygk",
"kpwedksb",
"sudyedgh",
"hyydhspc",
"uokepeon",
"ioecgpbw",
"lkmutdjy",
"pshtrmmz",
"kroueprw",
"xwublsln",
"davbfiem",
"wippdcas",
"cnnjktjt",
"jtgcztya",
"nbdutcpk",
"lebebegl",
"byswsvmu",
"dvrhjnmz",
"gzvwdqxu",
"gmpfpixt",
"eetccbqc",
"wxbzmtyz",
"nfpuhahj",
"kpzblmgq",
"auypcthp",
"luanyjde",
"pwmbrsxh",
"yugkpuhc",
"zvlglwne",
"rdtbnymo",
"ypbdveag",
"uxetfzxi",
"lvxhqpug",
"cmakitao",
"nfpuvcpi",
"nyrdursy",
"bmnxqdmg",
"tggaqphx",
"ebqocwik",
"lppmevzv",
"lvnmmcfl",
"mgjsjqln",
"vwmttobw",
"ahmdkmia",
"mxetfwxi",
"xrwduudz",
"hqnkjlvq",
"glrtsjyr",
"kprkzuvv",
"cjtganjz",
"ooaqzdxk",
"lxoaviio",
"hslnkxup",
"pfygvskj",
"fugthgms",
"mwogejct",
"nybvncbz",
"rfwrzyjd",
"fwbyjkhr",
"cmfogvwt",
"pwpnplfa",
"joxmcaeh",
"whyxmnvf",
"cgduliyz",
"dxdyzfpq",
"zbqlcuwk",
"firflzbq",
"xdghelzh",
"cznfxohv",
"rdaufnnr",
"zsgcalag",
"jrzjuidq",
"yawkpcsf",
"heloyror",
"uldiwqpw",
"okpydgfc",
"aytjeofw",
"xnfwzlez",
"nneorzjx",
"rdwjvmta",
"ainwxnas",
"tnkmegab",
"iwiuhpmk",
"edekyxip",
"kxxvmlhk",
"udferwsa",
"vyhaapmd",
"mtmnqzpg",
"ptzohtzv",
"efhufnnz",
"urdkdyzh",
"yjnouvbd",
"thclkscb",
"mmvdjtte",
"dsivsdkp",
"ommazwht",
"qcwdqhzk",
"qigvygwa",
"jvntlbmd",
"qpxgkfdb",
"nqasdieh",
"nffhnuvj",
"qixcnwly",
"uichhhgl",
"pzpqdbyu",
"wcngjzsk",
"ejugtmos",
"jbyxfsix",
"oqckcobc",
"tvnxlkvt",
"rrlggecb",
"sfyhlmkn",
"nadikadl",
"jeubkdbq",
"gonkgvab",
"xzskvofy",
"ibapazlb",
"gpqcgned",
"lvskmblm",
"vochfalb",
"uzzrcljz",
"fuhnzlss",
"kgqrvfog",
"xtctngmk",
"fkopdbku",
"ejhopiqg",
"bhjuiikq",
"dphnscrm",
"utvwdorg",
"hjrgjfth",
"lfzygyyy",
"qnkxyxlm",
"iwiffosx",
"qouzchvg",
"hvwqvxhw",
"nczbpucj",
"tgdsahph",
"ccvsxnpb",
"zqykmxbs",
"gfsswdut",
"jeiyknwo",
"rahvwzmr",
"yonmgbxi",
"nwuczfdr",
"jiispjyn",
"gehydavl",
"ghvlnljs",
"gaerupxc",
"objzhajd",
"qsibzaum",
"xhbojnbs",
"nykwucum",
"prgabpch",
"hezzgeoc",
"sxiqogzh",
"tuskyutg",
"lgafyodf",
"jxvvrjwx",
"oebuabir",
"qvdbbfrn",
"jplrzdjt",
"pqkpjdnc",
"wcmnokpx",
"qfoyxeax",
"yfyvprce",
"xojmqboi",
"jvfmcxjn",
"pslauuvt",
"vlvrizqg",
"qgzirvqv",
"vrkqfuwf",
"hhtinail",
"ioecucue",
"qshkemzo",
"ylseohek",
"svaqebui",
"takjrpnu",
"hrvqhlue",
"enumsbdx",
"waosyzfe",
"ouzibadf",
"ylqzlhsr",
"xesfwpcp",
"mkseaapu",
"ixpyzdke",
"kftxpmgd",
"wcbrqrua",
"iclrctfo",
"pguazprz",
"elgvmzmz",
"dguzpmar",
"qaovgsxm",
"hjxaakpz",
"rumgmqwf",
"pilipgru",
"ewtrmfjc",
"nsdeomwi",
"aucrjgzq",
"ebyrdicj",
"bvcacqtz",
"wjfustty",
"saahqqzi",
"kogwimsb",
"fhbtgnao",
"ofqowitr",
"rdnvwowd",
"aytcydvg",
"bmtljhdw",
"cjmtqcwm",
"vjepjxnx",
"fojibpga",
"npawksib",
"qkjaqrhz",
"dszkawfz",
"idqccfnn",
"yqtgayil",
"ufrqxrtj",
"mvecaukm",
"vkteopvi",
"dhfwwylt",
"igkbfhdx",
"zdvllwsn",
"hsedlmnd",
"apmcophg",
"yllwzjmu",
"gdzzyeqi",
"rzyqtoig",
"xjolcltb",
"ixxzpqlv",
"synujyzi",
"umervtrw",
"xysbjydr",
"yeywrrxc",
"tzgnewzc",
"vnphmnze",
"kkudnbkf",
"jqphaagv",
"ztlmyhmw",
"mhbbring",
"vlpnmzaq",
"ghwuixap",
"wktiwnpx",
"rbugtbqz",
"kkhedbnt",
"bryeqkmb",
"wcdnhcij",
"uhxixbol",
"ndkswawo",
"lrzovgcw",
"afihkyxc",
"wkzpodee",
"tqrmfacs",
"wlyxwgor",
"yeitnczn",
"bnozzykq",
"qoxrnjqc",
"xbzodqck",
"wzyrtfqt",
"odnhhbdl",
"kdblluxl",
"xzoerezu",
"vwrpwvle",
"lnahdnuf",
"kwrnedhq",
"fbwprhhf",
"dkgycbqn",
"kmjajkda",
"fzrwjkaa",
"avytimci",
"ayrsdhtp",
"meffhxoo",
"ghqbnvby",
"oggqytlo",
"ojtdckks",
"gtbjgqfx",
"jqkupaek",
"cmdzqfdo",
"smargvov",
"savskjrm",
"zilzpxgd",
"zqfktwjf",
"rsarxelu",
"odtqqnlp",
"fbwxjvvd",
"yqclkrat",
"gmmmdrye",
"qijqvzbj",
"ragmubct",
"gffgtluf",
"hiqkmiom",
"prxgwyii",
"xamwdlld",
"gavpfbxs",
"mpkfilwo",
"vvozqkfu",
"ccbdvzuy",
"duzvfxdp",
"qcvsbeys",
"akbhjcyp",
"dnplpcqs",
"bzvajkkv",
"yionjich",
"vlhrivqa",
"eklqhjwt",
"zlhmwatm",
"eiiueoct",
"zbcztogj",
"msxwmbsg",
"dpdvhoqc",
"gwljnfuo",
"alszfqbn",
"kzwbfcxt",
"irjfsuod",
"ljebgqjd",
"dklfwjbk",
"tscvzkko",
"wvwcplpd",
"iewadhyw",
"qwngxyeo",
"shklqqvu",
"hduiuhsf",
"binjsify",
"puapudwl",
"piszohps",
"rccnzrrn",
"hocsgqvh",
"vnodhywj",
"lmtmroeq",
"ekqammsw",
"lwqbipzs",
"bwhuyeby",
"owwozald",
"nowfwxnn",
"ooadouba",
"pldmnaww",
"sumhyutk",
"cxenygty",
"nqnjcwxg",
"veklrmyv",
"ffvimwbo",
"wywlhsav",
"cqgnbbhj",
"majlpxbs",
"iysdvxxd",
"cnsunofx",
"eixebniw",
"zpvyhttp",
"ftrbqnif",
"ddttvdyl",
"fwdxaniy",
"urbatveb",
"fijbgypg",
"ickimqxl",
"qcwavurw",
"mkmdbtsj",
"kwllaxge",
"ivlmxsgs",
"qmxgfqnu",
"rxovletq",
"tvdtiipz",
"wqaeqspc",
"xzfkxkqn",
"xbhqxste",
"ghfneagv",
"epiemcmq",
"qyseovqi",
"rapjeyxj",
"vbnlgjfv",
"kyqcxmls",
"dlzyyaqt",
"tbbjzwqj",
"mizphxvx",
"pamlbpte",
"revcferf",
"oouedwik",
"ymbatasm",
"aeszvcca",
"teirneaq",
"acrluwwg",
"ytoountd",
"hpxikugi",
"hmmoncon",
"aiktuico",
"dklpihab",
"mphjokkv",
"ueocpnry",
"bulrjcvm",
"nrsegeao",
"cflobpzl",
"sivytxsq",
"sjvzthwm",
"ltkxmvel",
"wmgoysrp",
"nrgjyvcn",
"usdpstyb",
"zefhvtmr",
"vlqhpkup",
"kukdtoyj",
"obyhxscm",
"eoecwepi",
"xkqcqpif",
"xtupijxg",
"hjbfeqgp",
"ohskaxva",
"acimoqlz",
"bvmbrwii",
"gohlekof",
"bgrnzyxm",
"rstnmucn",
"xbbskwej",
"whzvzyww",
"udtsgqax",
"oqcwhggu",
"zuikbmbc",
"bnqieolu",
"lzkdsxef",
"pxfzsrkk",
"addllsuq",
"ctmpeffv",
"ayuymejt",
"rubisjfv",
"kyiawgye",
"pbrejbnc",
"eiiplpud",
"vhfjnrzy",
"yjjnxvbm",
"eapstgjd",
"jtffvmmo",
"tjkdxvlu",
"rjuchthb",
"vrhioetj",
"twwvmogj",
"infjgjpu",
"lgkgbzyx"};
        ArrayList<String> c1 = new ArrayList();
        ArrayList<String> c2 = new ArrayList();
        ArrayList<String> c3 = new ArrayList();
        ArrayList<String> c4 = new ArrayList();
        ArrayList<String> c5 = new ArrayList();
        ArrayList<String> c6 = new ArrayList();
        ArrayList<String> c7 = new ArrayList();
        ArrayList<String> c8 = new ArrayList();
        
        for(String str : list){
            char[] array = str.toCharArray();
            
            c1.add(Character.toString(array[0]));
            c2.add(Character.toString(array[1]));
            c3.add(Character.toString(array[2]));
            c4.add(Character.toString(array[3]));
            c5.add(Character.toString(array[4]));
            c6.add(Character.toString(array[5]));
            c7.add(Character.toString(array[6]));
            c8.add(Character.toString(array[7]));
        }
        
        int max = 1000;
        String p1 = "";
        for (String s : c1) {
            if(Collections.frequency(c1, s) < max){
                max = Collections.frequency(c1, s);
                p1 = s;
            }
        }
        
        max = 1000;
        String p2 = "";
        for (String s : c2) {
            if(Collections.frequency(c2, s) < max){
                max = Collections.frequency(c2, s);
                p2 = s;
            }
        }
        
        max = 1000;
        String p3 = "";
        for (String s : c3) {
            if(Collections.frequency(c3, s) < max){
                max = Collections.frequency(c3, s);
                p3 = s;
            }
        }
        
        max = 1000;
        String p4 = "";
        for (String s : c4) {
            if(Collections.frequency(c4, s) < max){
                max = Collections.frequency(c4, s);
                p4 = s;
            }
        }
        
        max = 1000;
        String p5 = "";
        for (String s : c5) {
            if(Collections.frequency(c5, s) < max){
                max = Collections.frequency(c5, s);
                p5 = s;
            }
        }
        
        max = 1000;
        String p6 = "";
        for (String s : c6) {
            if(Collections.frequency(c6, s) < max){
                max = Collections.frequency(c6, s);
                p6 = s;
            }
        }
        
        max = 1000;
        String p7 = "";
        for (String s : c7) {
            if(Collections.frequency(c7, s) < max){
                max = Collections.frequency(c7, s);
                p7 = s;
            }
        }
        
        max = 1000;
        String p8 = "";
        for (String s : c8) {
            if(Collections.frequency(c8, s) < max){
                max = Collections.frequency(c8, s);
                p8 = s;
            }
        }
        
        System.out.println(p1+p2+p3+p4+p5+p6+p7+p8);
    }
}
